// <copyright file="PreValidateSmartintForEntityDelete.cs" company="">
// Copyright (c) 2013 All Rights Reserved
// </copyright>
// <author></author>
// <date>11/27/2013 4:45:25 PM</date>
// <summary>Implements the PreValidateSmartintForEntityDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace Smartint.SmartintPlugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;

    /// <summary>
    /// PreValidateSmartintForEntityDelete Plugin.
    /// </summary>    
    public class PreValidateSmartintForEntityDelete : BaseSmartintForEntityPlugin
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreValidateSmartintForEntityDelete"/> class.
        /// </summary>
        public PreValidateSmartintForEntityDelete()
            : base(typeof(PreValidateSmartintForEntityDelete))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(10, "Delete", "qg_smartintforentity", new Action<LocalPluginContext>(ExecutePreValidateSmartintForEntityDelete)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePreValidateSmartintForEntityDelete(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            Entity entity = GetTargetEntity(localContext);
            if (entity == null) return;

            var entityInfo = GetEntityInfo(entity);
            SystemForm systemForm = GetSystemForm(localContext, entityInfo);
            FormType form = Deserialize<FormType>(systemForm.FormXml);

            form = FixFormNavigation(form);

            form.Navigation.NavBar.Items = RemoveItem(form.Navigation.NavBar.Items);

            string result = Serialize<FormType>(form);

            if (result.Equals(systemForm.FormXml)) return;

            systemForm.FormXml = result;
            UpdateSystemForm(localContext, systemForm);
            PublishSystemForm(localContext, entityInfo.Item1);
        }
    }
}
